import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/Header';
import './globals.css';
config.autoAddCss = false;

const interFonts = Inter({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
	title: 'weraldcodev',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const header = <Header />;
	return (
		<html lang="en">
			<body
				className={`antialiased ${interFonts.className} w-full flex place-content-center `}
			>
				<div className="w-full md:w-[768px] lg:w-[1280px] ">
					{header}
					{children}
				</div>
			</body>
		</html>
	);
}
