import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/Header';
import './globals.css';

const interFonts = Inter({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const header = <Header />;
	return (
		<html lang="en">
			<body className={`antialiased ${interFonts.className}`}>
				{header}
				{children}footer
			</body>
		</html>
	);
}
